{% set name = "opentelemetry-propagator-b3" %}
{% set version = "1.34.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_propagator_b3-{{ version }}.tar.gz
  sha256: e1540f0333b2748d5c042cbb825ee9d6d9241c134985663401c43a10b68ce275

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - deprecated >=1.2.6
    - opentelemetry-api ~=1.3
    # - typing_extensions >=4.5.0
    # - typing_extensions >=4.5.0

test:
  imports:
    - opentelemetry.propagators.b3
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/master/propagator/opentelemetry-propagator-b3
  summary: OpenTelemetry B3 Propagator
  license: Apache-2.0
  license_file: LICENSE
  description: This library provides a propagator for the B3 format

extra:
  recipe-maintainers:
    - twoodwark
