{% set name = "opentelemetry-propagator-b3" %}
{% set version = "1.35.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_propagator_b3-{{ version }}.tar.gz
  sha256: 5e5c7822d515fba7ee4ab92314e7a9e8c26ce9fc2aac5d56498ca3c5ad4220a6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - deprecated >=1.2.6
    - opentelemetry-api ~=1.3
    # - typing_extensions >=4.5.0
    # - typing_extensions >=4.5.0
    # - typing_extensions >=4.5.0

test:
  imports:
    - opentelemetry.propagators.b3
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/master/propagator/opentelemetry-propagator-b3
  summary: OpenTelemetry B3 Propagator
  license: Apache-2.0
  license_file: LICENSE
  description: This library provides a propagator for the B3 format

extra:
  recipe-maintainers:
    - twoodwark
