{% set name = "opentelemetry-propagator-b3" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 143876de64dfa0e3ce117f06d9837e326adae3abde1afbf7c66fcbf2d2e52d30

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - opentelemetry-api ==0.17b0
    - python >=3.5

test:
  imports:
    - opentelemetry.propagators.b3
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/master/propagator/opentelemetry-propagator-b3
  summary: OpenTelemetry B3 Propagator
  license: Apache-2.0
  license_file: LICENSE
  description: This library provides a propagator for the B3 format

extra:
  recipe-maintainers:
    - twoodwark
